# Generated by Django 3.1.5 on 2021-06-29 19:34

from django.db import migrations, models
import posts.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('34226d7e-60b1-4397-8895-85c9c0669763'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('picture', models.ImageField(blank=True, upload_to=posts.models.profile_path, verbose_name='foto de perfil')),
            ],
            options={
                'verbose_name': 'autor',
                'verbose_name_plural': 'autores',
                'ordering': ['name'],
            },
        ),
    ]
