# Generated by Django 3.1.5 on 2021-06-29 20:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('slug', models.SlugField(unique=True, verbose_name='identificador')),
            ],
            options={
                'verbose_name': 'categoria',
                'ordering': ['slug'],
            },
        ),
    ]
