# Generated by Django 3.1.5 on 2021-06-29 21:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_create_category_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=150, verbose_name='titulo')),
                ('summary', models.CharField(max_length=200, verbose_name='sumário')),
                ('first_paragraph', models.TextField(max_length=450, verbose_name='primeiro paragrafo')),
                ('body', models.TextField(verbose_name='conteúdo')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.author', verbose_name='autor')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.category', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'artigo',
                'ordering': ['title'],
            },
        ),
    ]
